### ISSUE TITLE
exec can't handle certain field names beyond keywords

### ISSUE THREAD

**Issue by jmaroeder** [pcattori/maps#37]
The way `namedfixedkeymap` and `namedfrozenmap` are created in the current version of code, there are a couple additional field names that aren't supported beyond what are already accounted for in the `_validate_name` method.

The template code is:
```
def __init__(self, {args}):
    super(type(self), self).__init__()
    self._data = collections.OrderedDict({kwargs})
```

Because each of the field names gets inserted into `{args}`, the following field names are forbidden but not currently caught:
- `type`
- `self`
- `collections`

Here's code demonstrating each of the errors:

```
>>> Foo = maps.namedfrozen('Foo', ['type'])

>>> foo = Foo('abc')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-eb714c1f9e6f> in <module>()
----> 1 foo = Foo('abc')

<string> in __init__(self, type)

TypeError: 'str' object is not callable

>>> Bar = maps.namedfrozen('Bar', ['self'])
Traceback (most recent call last):

  File "/Users/jamesallen/.pyenv/versions/3.6.1/envs/cf2-local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-59-53de955fd15f>", line 1, in <module>
    Bar = maps.namedfrozen('Bar', ['self'])

  File "/Users/jamesallen/.pyenv/versions/3.6.1/envs/cf2-local/lib/python3.6/site-packages/maps/__init__.py", line 29, in namedfrozen
    return NamedFrozenMapMeta(typename, fields)

  File "/Users/jamesallen/.pyenv/versions/3.6.1/envs/cf2-local/lib/python3.6/site-packages/maps/namedfrozenmap.py", line 104, in __new__
    exec(template.format(args=args, kwargs=kwargs), namespace)

  File "<string>", line 1
SyntaxError: duplicate argument 'self' in function definition


>>> Baz = maps.namedfrozen('Baz', ['collections'])

>>> baz = Baz('abc')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-61-10871cae25dc> in <module>()
----> 1 baz = Baz('abc')

<string> in __init__(self, collections)

AttributeError: 'str' object has no attribute 'OrderedDict'
```

The simplest fix is to disallow these field names, but it also shouldn't be much more work to come up with unique identifiers for `self`, `type`, and `collections`. I'll look into it and submit a PR shortly

**Comment by jmaroeder** [comment]
`super` is also affected:

```
>>> Moo = maps.namedfrozen('Moo', ['super'])

>>> moo = Moo('abc')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-72-0b46a560680c> in <module>()
----> 1 moo = Moo('abc')

<string> in __init__(self, super)

TypeError: 'str' object is not callable
```

**Comment by pcattori** [comment]
@jamesmallen i took the tests you wrote in #38 but replaced your solution with the underscore solution I proposed as a comment to #38 . Should be good to go 😄
